use voting_system

insert into account (student_name, password) values ('TNKompanska', 'kompanska');
insert into account (student_name, password) values ('VNTeneva', 'teneva');
insert into account (student_name, password) values ('Rosetta Sparham', 'w1.RX8');
insert into account (student_name, password) values ('Reena Pren', 'm0th@~sag%');
insert into account (student_name, password) values ('Andrew Ringsell', 'r9&CnJ#t');
insert into account (student_name, password) values ('Garry Keuntje', 'w1y{%6b');
insert into account (student_name, password) values ('Fonsie Dickerson', 'e1}V,MQz,2');
insert into account (student_name, password) values ('Osmund Reedyhough', 'k5&TOe');
insert into account (student_name, password) values ('Viole Di Roberto', 'n5\2T');
insert into account (student_name, password) values ('Rudd Trenbay', 't4_Vow`?');
insert into account (student_name, password) values ('Reider McDuffie', 'q7,A+@~0%');
insert into account (student_name, password) values ('Jeannie Girardot', 'i1qAjx&F}Z');
insert into account (student_name, password) values ('Geoffry Baudts', 'q7qg@F$WVp');
insert into account (student_name, password) values ('Joelynn Roden', 'c6V5PD6{uL');
insert into account (student_name, password) values ('Nikola Bassil', 's3(1=>3W)');
insert into account (student_name, password) values ('Lanie Storek', 'u0t''#.@');
insert into account (student_name, password) values ('Clerkclaude Curtoys', 'n3Q9T&tT');
insert into account (student_name, password) values ('Marylinda Jaquest', 'v9nOJ');
insert into account (student_name, password) values ('Skippy Sprosson', 'm5dow');
insert into account (student_name, password) values ('Kat Squirrel', 'i7cj1mmK0w');
insert into account (student_name, password) values ('Hurley Tebbet', 'x1mGJB2>x)');
insert into account (student_name, password) values ('Alfons Lincke', 'l4%?\!KHi');
insert into account (student_name, password) values ('Lorettalorna Whodcoat', 'z0yXD(@g9Z');
insert into account (student_name, password) values ('Thornie Hagwood', 'a1qbarCg');
insert into account (student_name, password) values ('Phil Kirlin', 'a9e4U}gc');
insert into account (student_name, password) values ('Rodrigo Lyvon', 'k4Hw?#cK');
insert into account (student_name, password) values ('Nyssa Hoyer', 'm0p%H0(ZU{');
insert into account (student_name, password) values ('Helaine Bohey', 'o4l1wp\2');
insert into account (student_name, password) values ('Maurizio Rosenstiel', 'p2*VA+');
insert into account (student_name, password) values ('Fallon Farrey', 'w1fFI');
insert into account (student_name, password) values ('Irwinn Rodmell', 'b6g*,c0qK');
insert into account (student_name, password) values ('Anita Skeemer', 'y5qF~G');
insert into account (student_name, password) values ('Winfred Cardinal', 'q8D}eD');
insert into account (student_name, password) values ('Connie Hardern', 'y6@U{nQ"');
insert into account (student_name, password) values ('Shirleen Huthart', 'l8~_zt');
insert into account (student_name, password) values ('Domingo Hector', 'p3OoHz6U');
insert into account (student_name, password) values ('Christel Willerson', 'g3PU.0');
insert into account (student_name, password) values ('Dave Mosten', 'z8UaQ4@');
insert into account (student_name, password) values ('Skell Botger', 'v3r5>');
insert into account (student_name, password) values ('Amabelle Pheazey', 's0a$_$BI');
insert into account (student_name, password) values ('Lia O''Suaird', 'b6{{5#h|cH');
insert into account (student_name, password) values ('Bo Danzey', 's7O6a_0P');
insert into account (student_name, password) values ('Edgard Mechell', 'p0H?Ik!(7');
insert into account (student_name, password) values ('Heather Carus', 'l9ge>cmHrk');
insert into account (student_name, password) values ('Arliene Ayshford', 'y2A''bI92<X');
insert into account (student_name, password) values ('Vilhelmina Dandison', 'u2tI+$z0l+');
insert into account (student_name, password) values ('Darrel Di Claudio', 'p1Sv<qpN');
insert into account (student_name, password) values ('Wanda McIleen', 'c1NL`L1');
insert into account (student_name, password) values ('Curtis Pech', 's9..4sA''O#');
insert into account (student_name, password) values ('Olenolin Foro', 'a8wo~|{Ao');
insert into account (student_name, password) values ('Phillida Menault', 'd28QLCq');
insert into account (student_name, password) values ('Cassius Affleck', 'i5.Pl(6U');
