import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class UserLogin extends javax.swing.JFrame {
    Connection con = getConnection();
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
    }

    public Connection getConnection(){
        try {
            // Establish the connection
            con = DriverManager.getConnection("jdbc:sqlserver://SL152\\SQLEXPRESS;Database=voting_system;integratedSecurity=false;encrypt=false;", "admin", "admin12345");
            return con; // Return the connection object after successful connection
        } catch(Exception e)
        {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userText = new javax.swing.JTextField();
        passText = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        userText.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Username");
        jLabel1.setToolTipText("Enter your username");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password");
        jLabel2.setToolTipText("Enter your password, if forgotten contact Admin");

        jButton2.setBackground(new java.awt.Color(176, 229, 209));
        jButton2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jButton2.setText("LOGIN");
//        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseEntered(java.awt.event.MouseEvent evt) {
//               jButton2MouseEntered(evt);
//            }
//        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jButton2InputMethodTextChanged(evt);
            }
        });

        passText.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(176, 229, 209));
        jButton1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton1.setText("Main Menu");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton1)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(userText)
                                                        .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(9, 9, 9)
                                                .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String passId = userText.getText();
        String login = "SELECT * FROM account WHERE student_name = ? AND password = ? AND status = 'no'";
        String already = "SELECT * FROM account WHERE student_name = ? AND password = ? AND status = 'yes'";
        String incorrect = "SELECT * FROM account WHERE student_name = ? AND password = ?";

        String p = passText.getText();
        if (passId.isEmpty() || p.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a username and password!");
            return; // Stop further execution
        }

        try {
            Connection con = getConnection();
            pst = con.prepareStatement(login);
            pst.setString(1, userText.getText());
            pst.setString(2, passText.getText());
            rs = pst.executeQuery();

            PreparedStatement pst1 = con.prepareStatement(incorrect);
            pst1.setString(1, userText.getText());
            pst1.setString(2, passText.getText());
            ResultSet rs1 = pst1.executeQuery();

            PreparedStatement pst2 = con.prepareStatement(already);
            pst2.setString(1, userText.getText());
            pst2.setString(2, passText.getText());
            ResultSet rs2 = pst2.executeQuery();

            if (rs.next()) {
                rs.close();
                pst.close();
                JOptionPane.showMessageDialog(null, "Success!");
                setVisible(false);
                new VotingSystem(passId).setVisible(true);
            } else if (rs2.next()) {
                JOptionPane.showMessageDialog(null, "You have already voted!");
                userText.setText(null);
                passText.setText(null);
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect ID number AND Password!");
                userText.setText(null);
                passText.setText(null);
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        setVisible(false);
        MainMenu main = new MainMenu();
        main.setVisible(true);
        main.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton1MouseClicked


    private void jButton2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jButton2InputMethodTextChanged
        String passId = userText.getText();
        String login = "SELECT * FROM account WHERE student_name = ? AND password = ? AND status = 'no'";
        String already = "SELECT * FROM account WHERE student_name = ? AND password = ? AND status = 'yes'";
        String incorrect = "SELECT * FROM account WHERE student_name = ? AND password = ?";

        String u = userText.getText();
        String p = passText.getText();
        if (u.isEmpty() || p.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a username and password!");
            return; // Stop further execution
        }

        try {
            Connection con = getConnection();
            pst = con.prepareStatement(login);
            pst.setString(1, userText.getText());
            pst.setString(2, passText.getText());
            rs = pst.executeQuery();

            PreparedStatement pst1 = con.prepareStatement(incorrect);
            pst1.setString(1, userText.getText());
            pst1.setString(2, passText.getText());
            ResultSet rs1 = pst1.executeQuery();

            PreparedStatement pst2 = con.prepareStatement(already);
            pst2.setString(1, userText.getText());
            pst2.setString(2, passText.getText());
            ResultSet rs2 = pst2.executeQuery();

            if (rs.next()) {
                rs.close();
                pst.close();
                JOptionPane.showMessageDialog(null, "Success!");
                setVisible(false);
                new VotingSystem(passId).setVisible(true);
            } else if (rs2.next()) {
                JOptionPane.showMessageDialog(null, "You have already voted!");
                userText.setText(null);
                passText.setText(null);
            } else if (rs1.next()) {
                JOptionPane.showMessageDialog(null, "Incorrect ID number AND Password!");
                userText.setText(null);
                passText.setText(null);
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passText;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
