import javax.swing.*;
import java.sql.*;

public class VotingSystem extends javax.swing.JFrame {

    Connection con;
    ResultSet rs,rs1,rs2,rs3,rs4,rs5,rs6,rsAccount;
    PreparedStatement pst,pst1,pst2,pst3,pst4,pst5,pst6,pstAccount;

    /**
     * Creates new form voting
     */
    public VotingSystem() {
        initComponents();
        forms();
    }

    public VotingSystem(String passid) {
        initComponents();
        idreceive.setText(passid);
        forms();
    }

    public Connection getConnection(){
        try{                                                                        //username //database         =pass no password
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/voting_system","root","");
            return con;
        }
        catch(Exception e){
        }
        return null;
    }


    public void forms(){

        try{

            Connection con = getConnection();

            int pre=1;
            String president= "select candidate_name from candidate where position_id='"+pre+"'";
            pst1 = con.prepareStatement(president);
            rs1 = pst1.executeQuery();

            int vicepre=2;
            String vicepresident= "select candidate_name from candidate where position_id='"+vicepre+"'";
            pst2 = con.prepareStatement(vicepresident);
            rs2 = pst2.executeQuery();

            int secnum=3;
            String secretary = "select candidate_name from candidate where position_id='"+secnum+"'";
            pst3 = con.prepareStatement(secretary);
            rs3 = pst3.executeQuery();

            int treanum=5;
            String treasurer = "select candidate_name from candidate where position_id='"+treanum+"'";
            pst4 = con.prepareStatement(treasurer);
            rs4 = pst4.executeQuery();

            int audi=4;
            String auditor = "select candidate_name from candidate where position_id='"+audi+"'";
            pst5 = con.prepareStatement(auditor);
            rs5 = pst5.executeQuery();

            int pionum=6;
            String pio = "select candidate_name from candidate where position_id='"+pionum+"'";
            pst6 = con.prepareStatement(pio);
            rs6 = pst6.executeQuery();

            while(rs1.next()&&rs2.next() && rs3.next() &&rs4.next() &&rs5.next() &&rs6.next() ){
                presidentCB.addItem(rs1.getString(1));
                vicepresidentCB.addItem(rs2.getString(1));
                secretaryCB.addItem(rs3.getString(1));
                treasurerCB.addItem(rs4.getString(1));
                auditorCB.addItem(rs5.getString(1));
                pioCB.addItem(rs6.getString(1));
            }
        }

        catch(Exception e){
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PresidentGroup = new javax.swing.ButtonGroup();
        VicePresidentGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        idreceive = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        treasurerCB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        presidentCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        vicepresidentCB = new javax.swing.JComboBox<>();
        secretaryCB = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        auditorCB = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        pioCB = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new ViewportLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setText("Secretary");
        getContentPane().add(jLabel1, new SpringLayout.Constraints(Spring.constant(70), Spring.constant(210), Spring.constant(-1), Spring.constant(-1)));

        jButton2.setText("Vote now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new SpringLayout.Constraints(Spring.constant(210), Spring.constant(460), Spring.constant(110), Spring.constant(60)));
        getContentPane().add(idreceive, new SpringLayout.Constraints(Spring.constant(358), Spring.constant(27), Spring.constant(190), Spring.constant(-1)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("STUDENT ID NUMBER");
        getContentPane().add(jLabel6, new SpringLayout.Constraints(Spring.constant(150), Spring.constant(20), Spring.constant(-1), Spring.constant(29)));

        treasurerCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));
        getContentPane().add(treasurerCB, new SpringLayout.Constraints(Spring.constant(210), Spring.constant(250), Spring.constant(185), Spring.constant(35)));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new SpringLayout.Constraints(Spring.constant(650), Spring.constant(110), Spring.constant(130), Spring.constant(80)));

        presidentCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));
        presidentCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presidentCBActionPerformed(evt);
            }
        });
        getContentPane().add(presidentCB, new SpringLayout.Constraints(Spring.constant(210), Spring.constant(70), Spring.constant(185), Spring.constant(35)));

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel9.setText("Your Choices");
        getContentPane().add(jLabel9, new SpringLayout.Constraints(Spring.constant(590), Spring.constant(60), Spring.constant(-1), Spring.constant(-1)));

        jLabel10.setText("jLabel8");
        getContentPane().add(jLabel10, new SpringLayout.Constraints(Spring.constant(650), Spring.constant(230), Spring.constant(130), Spring.constant(80)));

        jLabel11.setText("jLabel8");
        getContentPane().add(jLabel11, new SpringLayout.Constraints(Spring.constant(520), Spring.constant(370), Spring.constant(130), Spring.constant(80)));

        jLabel12.setText("jLabel8");
        getContentPane().add(jLabel12, new SpringLayout.Constraints(Spring.constant(710), Spring.constant(360), Spring.constant(130), Spring.constant(80)));

        jLabel13.setText("jLabel8");
        getContentPane().add(jLabel13, new SpringLayout.Constraints(Spring.constant(520), Spring.constant(490), Spring.constant(130), Spring.constant(80)));

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel14.setText("Treasurer");
        getContentPane().add(jLabel14, new SpringLayout.Constraints(Spring.constant(70), Spring.constant(260), Spring.constant(-1), Spring.constant(-1)));

        jLabel15.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel15.setText("Vice PRESIDENT");
        getContentPane().add(jLabel15, new SpringLayout.Constraints(Spring.constant(0), Spring.constant(150), Spring.constant(-1), Spring.constant(-1)));

        vicepresidentCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));
        getContentPane().add(vicepresidentCB, new SpringLayout.Constraints(Spring.constant(210), Spring.constant(140), Spring.constant(185), Spring.constant(35)));

        secretaryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));
        getContentPane().add(secretaryCB, new SpringLayout.Constraints(Spring.constant(210), Spring.constant(200), Spring.constant(185), Spring.constant(35)));

        jLabel16.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel16.setText("Auditor");
        getContentPane().add(jLabel16, new SpringLayout.Constraints(Spring.constant(100), Spring.constant(320), Spring.constant(-1), Spring.constant(-1)));

        auditorCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));
        getContentPane().add(auditorCB, new SpringLayout.Constraints(Spring.constant(210), Spring.constant(310), Spring.constant(185), Spring.constant(35)));

        jLabel17.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel17.setText("PRESIDENT");
        getContentPane().add(jLabel17, new SpringLayout.Constraints(Spring.constant(60), Spring.constant(70), Spring.constant(-1), Spring.constant(-1)));

        pioCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));
        getContentPane().add(pioCB, new SpringLayout.Constraints(Spring.constant(210), Spring.constant(370), Spring.constant(185), Spring.constant(35)));

        jLabel18.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel18.setText("P.I.O");
        getContentPane().add(jLabel18, new SpringLayout.Constraints(Spring.constant(130), Spring.constant(370), Spring.constant(-1), Spring.constant(-1)));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new SpringLayout.Constraints(Spring.constant(720), Spring.constant(500), Spring.constant(300), Spring.constant(60)));

//        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String prs = presidentCB.getSelectedItem().toString();
        String updatePres = "UPDATE candidate SET points = points + 1 WHERE candidate_name ='"+prs+"' ";
        if (presidentCB.getSelectedItem().toString().equals(prs)){

            try{
                Connection con = getConnection();
                Statement state;
                state =con.prepareStatement(updatePres);
                state.execute(updatePres);
            }

            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Voted wrong!"+e);
            }
        }

        String vrs = vicepresidentCB.getSelectedItem().toString();
        String updateVice = "UPDATE candidate SET points = points + 1 WHERE candidate_name ='"+vrs+"' ";

        if (vicepresidentCB.getSelectedItem()==vrs){
            try{
                Connection con = getConnection();
                Statement state;
                state =con.prepareStatement(updateVice);
                state.execute(updateVice);
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Voted wrong!"+e);
            }
        }

        String ids=idreceive.getText();
        String updateid="Yes";
        String voters ="UPDATE account SET status = '"+updateid+"' WHERE id_number ='"+ids+"' ";

        try{
            Connection con = getConnection();
            Statement stateid;
            stateid =con.prepareStatement(voters);
            stateid.execute(voters);
        }
        catch(Exception e){
        }

        String sec = secretaryCB.getSelectedItem().toString();
        String updateSec = "UPDATE candidate SET points = points + 1 WHERE candidate_name ='"+sec+"' ";
        if (secretaryCB.getSelectedItem()==sec){
            try{
                Connection con = getConnection();
                Statement state;
                state =con.prepareStatement(updateSec);
                state.execute(updateSec);
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Voted wrong!"+e);
            }
        }

        String tres = treasurerCB.getSelectedItem().toString();
        String updateTres = "UPDATE candidate SET points = points + 1 WHERE candidate_name ='"+tres+"' ";
        if (treasurerCB.getSelectedItem()==tres){

            try{
                Connection con = getConnection();
                Statement state;
                state =con.prepareStatement(updateTres);
                state.execute(updateTres);
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Voted wrong!"+e);
            }
        }

        String aud = auditorCB.getSelectedItem().toString();
        String updateAud = "UPDATE candidate SET points = points + 1 WHERE candidate_name ='"+aud+"' ";
        if (auditorCB.getSelectedItem()==aud){
            try{
                Connection con = getConnection();
                Statement state;
                state =con.prepareStatement(updateAud);
                state.execute(updateAud);
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Voted wrong!"+e);
            }
        }

        String pio = pioCB.getSelectedItem().toString();
        String updatePio = "UPDATE candidate SET points = points + 1 WHERE candidate_name ='"+pio+"' ";
        if (pioCB.getSelectedItem()==pio){
            try{
                Connection con = getConnection();
                Statement state;
                state =con.prepareStatement(updatePio);
                state.execute(updatePio);
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Voted wrong!"+e);
            }
        }

        String id = idreceive.getText().toString();
        Connection con = getConnection();
        try{
            String status="yes";
            String search ="select student_name from account where id_number='"+id+"'";
            String updtestudentid ="UPDATE account set status='"+status+"'   where id_number='"+id+"'  ";
            Statement searchst = con.createStatement();
            ResultSet setthis = searchst.executeQuery(search);
            Statement stupdate = con.createStatement();
            stupdate.executeUpdate(updtestudentid);
            JOptionPane.showMessageDialog(null,"Thank you ");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Wrong ang ga vote!");
        }
        JOptionPane.showMessageDialog(null,"Thank you For Voting");
    }//GEN-LAST:event_jButton2ActionPerformed


    private void presidentCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presidentCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presidentCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup PresidentGroup;
    private javax.swing.ButtonGroup VicePresidentGroup;
    private javax.swing.JComboBox<String> auditorCB;
    private javax.swing.JTextField idreceive;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> pioCB;
    private javax.swing.JComboBox<String> presidentCB;
    private javax.swing.JComboBox<String> secretaryCB;
    private javax.swing.JComboBox<String> treasurerCB;
    private javax.swing.JComboBox<String> vicepresidentCB;
    // End of variables declaration//GEN-END:variables
}
